name: "hospital_bi"
version: "1.0.0"
config-version: 2
profile: "hospital_bi"

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  hospital_bi:
    +materialized: view
